package uniandes.cupi2.magicalCreatures.userInterface;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Contains the panel that holds the buttons to perform different actions.
 */
public class ActionsPanel extends JPanel implements ActionListener {
	
	// -----------------------------------------------------------------
	// Constants
	// -----------------------------------------------------------------
	
	/**
	 * Command to view the creatures in a row.
	 */
	public final static String CREATURES_IN_ROW = "Creatures in row";
	
	/**
	 * Command to view the creatures in a column.
	 */
	public final static String CREATURES_IN_COLUMN = "Creatures in column";
	
	/**
	 * Command to view the points still available in a quadrant.
	 */
	public final static String POINTS_IN_QUADRANT = "Points in quadrant";
	
	/**
	 * Command to view the creature with the highest points yet to be discovered.
	 */
	public final static String HIGHEST_POINT_CREATURE = "Highest-point creature";
	
	// -----------------------------------------------------------------
	// Attributes of the interface
	// -----------------------------------------------------------------
	
	/**
	 * Button to view the creatures in a row.
	 */
	private JButton creaturesInRowBtn;
	
	/**
	 * Button to view the creatures in a column.
	 */
	private JButton creaturesInColumnBtn;
	
	/**
	 * Button to view the points still available in a quadrant.
	 */
	private JButton pointsInQuadrantBtn;
	
	/**
	 * Button to view the creature with the highest points yet to be discovered.
	 */
	private JButton highestPointCreatureBtn;
	
	// -----------------------------------------------------------------
	// Attributes
	// -----------------------------------------------------------------
	
	/**
	 * Principal window of the application.
	 */
	private MagicalCreaturesUserInterface principal;
	
	/**
	 * Creates a new panel containing the actions of the interface.
	 *
	 * @param pPrincipal Principal window of the application.
	 */
	public ActionsPanel(MagicalCreaturesUserInterface pPrincipal) {
		principal = pPrincipal;
		setBackground(new Color(48, 41, 84));
		setLayout(new GridLayout(1, 4, 0, 20));
		TitledBorder border = new TitledBorder("Actions");
		border.setTitleColor(Color.WHITE);
		setBorder(border);
		
		// Create "creatures in row" button and add to navigation panel.
		creaturesInRowBtn = new JButton("Creatures in row");
		creaturesInRowBtn.setActionCommand(CREATURES_IN_ROW);
		creaturesInRowBtn.addActionListener(this);
		creaturesInRowBtn.setEnabled(false);
		add(creaturesInRowBtn);
		
		// Create "creatures in column" button and add to navigation panel.
		creaturesInColumnBtn = new JButton("Creatures in column");
		creaturesInColumnBtn.setActionCommand(CREATURES_IN_COLUMN);
		creaturesInColumnBtn.addActionListener(this);
		creaturesInColumnBtn.setEnabled(false);
		add(creaturesInColumnBtn);
		
		// Create "points in quadrant" button and add to navigation panel.
		pointsInQuadrantBtn = new JButton("Points in quadrant");
		pointsInQuadrantBtn.setActionCommand(POINTS_IN_QUADRANT);
		pointsInQuadrantBtn.addActionListener(this);
		pointsInQuadrantBtn.setEnabled(false);
		add(pointsInQuadrantBtn);
		
		// Create "Highest-point creature" button and add to navigation panel.
		highestPointCreatureBtn = new JButton("Highest-point creature");
		highestPointCreatureBtn.setActionCommand(HIGHEST_POINT_CREATURE);
		highestPointCreatureBtn.addActionListener(this);
		highestPointCreatureBtn.setEnabled(false);
		add(highestPointCreatureBtn);
		
	}
	
	/**
	 * Handles the events that are generated by the user.
	 *
	 * @param pEvent User generated event.
	 */
	public void actionPerformed(ActionEvent pEvent) {
		String command = pEvent.getActionCommand();
		
		switch (command) {
			case CREATURES_IN_ROW:
				principal.seeCreaturesInRow();
				break;
			case CREATURES_IN_COLUMN:
				principal.seeCreaturesInColumn();
				break;
			case POINTS_IN_QUADRANT:
				principal.seePointsInQuadrant();
				break;
			default:
				principal.seeHighestPointCreature();
				break;
		}
	}
	
	
	/**
	 * Updates the panel if the load button is pressed in the options panel.
	 * <b>post: </b> The actions panel buttons are enabled.
	 */
	public void enableActionsPanel() {
		creaturesInRowBtn.setEnabled(true);
		creaturesInColumnBtn.setEnabled(true);
		pointsInQuadrantBtn.setEnabled(true);
		highestPointCreatureBtn.setEnabled(true);
		
	}
	
	/**
	 * Updates the panel if the game is won or lost.
	 * <b>post: </b> The actions panel buttons are disabled.
	 */
	public void disableActionsPanel() {
		creaturesInRowBtn.setEnabled(false);
		creaturesInColumnBtn.setEnabled(false);
		pointsInQuadrantBtn.setEnabled(false);
		highestPointCreatureBtn.setEnabled(false);
	}
	
}
